---
abstract: 'Extract getopt configuration from POD'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Config-FromPod
requires:
  Pod::Simple: 0
  parent: 0
  perl: 5.008
version: v0.0.1
